# FROM ghcr.io/ublue-os/fedora-toolbox:latest

FROM quay.io/fedora/fedora:43-x86_64

LABEL "dev.dbox"="true"

RUN dnf update -y && \
dnf install -y bash-completion vim tmux fastfetch fzf jq yq zoxide nodejs sqlite3 sqlite-analyzer
